server:
  port: 9090


spring:
  webflux:
    base-path: /api/v1.0/company
  application:
    name: users
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: test
    password: test
  sql:
    init:
      mode: embedded

logging:
  level:
    io:
      r2dbc:
        h2: DEBUG
jwt:
  secret: f973594fec7723858f405e4d022ed191b5fcb9d307692501c61088852dc270c8

security:
  public-paths:
    - POST:/api/v1.0/company/users
    - POST:/api/v1.0/company/auth/login
    - GET:/api/v1.0/company/users/stream