server:
  port: 9090


spring:
  webflux:
    base-path: /api/v1.0/company
  application:
    name: users
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: test
    password: test
  sql:
    init:
      mode: embedded


